2 New Commands
distubejs/example pull request #4
Opened 2020-12-30 16:44 UTC by pgamerxdev

I just added 2 more commands - pause and resume in example.
I will be adding more over time

2021-01-01 09:27 UTC, skick1234 requested changes

2021-01-01 09:27 UTC, skick1234 commented on commands/pause.js
> +         client.distube.pause(message)
I think we should unpause the song if it have been paused already.
```suggestion
        let queue = client.distube.getQueue(message)
        if (!queue) return message.channel.send(`${client.emotes.error} | There is nothing in the queue right now!`)
        if (queue.pause) {
            client.distube.resume(message)
            return message.channel.send("Resumed the song for you :)")
        }
        client.distube.pause(message)
```

2021-01-01 09:27 UTC, skick1234 commented on commands/resume.js
> +         client.distube.resume(message)
Linting
```suggestion
        let queue = client.distube.getQueue(message)
        if (!queue) return message.channel.send(`${client.emotes.error} | There is nothing in the queue right now!`)
        client.distube.resume(message)
```

2021-01-01 12:05 UTC, pgamerxdev commented
Everything looks fine no 
Kindly recheck

2021-01-01 18:46 UTC, skick1234 approved these changes
Thanks for the pr 😉

2021-01-01 18:48 UTC, merged

2021-01-02 03:11 UTC, pgamerxdev commented
No problem buddy ;)